---
arch:
  - amd64
  - ppc64le
language: ruby
rvm:
  - 2.5.8
  - 2.6.6
cache: bundler
before_script:
  - |
    if [[ "$TRAVIS_CPU_ARCH" == "amd64" ]]; then 
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
      ./cc-test-reporter before-build
    fi
after_script: 
  - |
    if [[ "$TRAVIS_CPU_ARCH" == "amd64" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    else bundle exec codeclimate-test-reporter
    fi
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/0357efbc3cba43430d2b
    on_success: change
    on_failure: always
    on_start: never
